### ISSUE TITLE
Title is missing when using `LayoutInflater` to add views to the dialog

### ISSUE THREAD

**Issue by dentex** [danoz73/QustomDialog#3]
If you inflate i.e. an TextView or a CheckBox and then do `setView` on the dialog, the title is missing.

**Comment by danoz73** [comment]
If you want to add a custom view to the dialog you should use the `setCustomView(int resId, Context c)` function. The usage for this functionality is described in the README.

**Comment by dentex** [comment]
OK thank you very much.
What about issue #2? I had the same problem.

**Comment by danoz73** [comment]
Working on it now. Will push solution soon :)

**Comment by dentex** [comment]
Great!
