### ISSUE TITLE
ListView inside QustomDialog

### ISSUE THREAD

**Issue by Shadie6** [danoz73/QustomDialog#8]
I create a QustomDialog and then I use setContentView to inflate a new layout, which contains a ListView.
How can I reach that ListView?

final QustomDialogBuilder chooseDeliveryCustomerDialog = new QustomDialogBuilder(getActivity());
chooseDeliveryCustomerDialog.setCustomView(R.layout.custom_add_associate, getActivity());
final AlertDialog dialog = chooseDeliveryCustomerDialog.create();
ListView customerList = (ListView) dialog.findViewById(R.id.custom_associate_listView);

This are the steps I do.
With every item dialog.findViewById(...) works fine, but with ListView it gives NullPointer.

**Comment by logan676** [comment]
this project is really helpful. But I have the same requirements with @Shadie6, I need to add a listview to QustomDialog and response to user click event. I also tried to use setItems() it resulted like below:
![device-2014-09-29-142204](https://cloud.githubusercontent.com/assets/2975850/4437834/0ce77086-47a1-11e4-9b7d-cc9f318d77c5.png)

I wonder how to move these items to the bottom of the title.

**Comment by Shadie6** [comment]
The answer to my question is: 
before findViewById(..) command, I have to show the dialog with dialog.show().

@Logan676 for your problem I think you should create a layout and inflate it to the QustomDialog using qustomDialog.setCustomView(R.layout.your_layout), then create and show the relative AlertDialog and last, after dialog.show(), manage the onClickListener or onItemClickListener on the List.
